### ISSUE TITLE
选择windows 11 pro 后依然生成windows 10 pro的配置

### ISSUE THREAD

**Issue by Goojoe** [dsx42/UnattendTool#1]
选择的是默认的windows 11，未输入序号选择。然后生成了
```
<Key>/IMAGE/NAME</Key>
<Value>Windows 10 Pro</Value>
```
全自动安装就需要手动选择，setup.exe界面仅有windows 11 pro。手动更改Windows 11 Pro后没问题

**Comment by dsx42** [comment]
感谢提出问题，已修复，请下载 v2024.9.21 版本使用。

原因说明：微软一开始发布的 Windows 11 镜像，镜像名是 Windows 10，而不是 Windows 11，但是最新的 ISO 已经是 Windows 11 了，所以出现此问题。具体从哪个版本的 ISO 开始改为 Windows 11，就没有细究了。

**Comment by Goojoe** [comment]
希望可选配置安装/格式化硬盘的选项：配置文件无`<Disk>和<image>`

这个选择安装到系统的分区可以用WinNTsetup手动选。之前重装系统，电脑硬盘顺序变了。直接把我别的盘格式化了，难受啊
